### ISSUE TITLE
mutex on every node

### ISSUE THREAD

**Issue by ekg** [pangenome/odgi#105]
By adding a mutex to every node, it should be possible to implement distributed editing of the graph. This in turn could be used to speed up builds, by making them multithreaded.

**Comment by JervenBolleman** [comment]
A mutex on every node seems very expensive memory wise.
What about a mutex hash table.
e.g. hash the nodeId to just enough bits for every cpu core in the machine.
then use that hash value to get a mutex.

This would limit the number of mutexes to the number of cpu's in the machine which requires a lot less memory.

**Comment by ekg** [comment]
An atomic bitvector would be enough as well, and minimal in terms of memory usage. But we'd have to spin on each set bit.

**Comment by subwaystation** [comment]
@ekg implemented this successfully.
