### ISSUE TITLE
Visulization of vg file from Progressive Cactus Pangenome Pipeline

### ISSUE THREAD

**Issue by SimonaSecomandi** [pangenome/odgi#228]
Hello,

I created a pangenome for the Barn swallow with the Cactus Pangenome Pipeline (https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/pangenome.md). I Aligned the chromosome-level assembly for the species with 5 assemblies of 5 other barn swallow individuals assembled with Hifiasm starting from PacBio HiFi reads (contig-level assemblies). In the Cactus pipeline, the chromosome-level assembly was choosen as the reference.

The final file from the Pangenome pipeline is a .vg file, that I have converted to .gfa with vgtools:

vg view --threads 32 Hirundo.vg > Hirundo.gfa

Then I coverted it in odgi format and sort it:

odgi build -g Hirundo.gfa -o - -p | odgi sort --threads=32 -i - -o Hirundo_sorted.og -p bSnSnS

Finally, I visualized it with odgi viz:

odgi viz -i Hirundo_sorted.og -o Hirundo_sorted.og.png -x 1920 -y 1080 -t 32

However, I can't understand the final image (below).. do you have any suggestions on how to sort my pangenome and visualize the different chromosomes of the reference and their corresponding aligned contigs from the other 5 individals (for example adding the chr names)?

![Hirundo_sorted22 og](https://user-images.githubusercontent.com/45236153/110975550-2d987f80-8360-11eb-8c18-766c74f35aa6.png)

Many thanks, 

Simona

**Comment by AndreaGuarracino** [comment]
Hi @SimonaSecomandi, looking at your commands, it seems you are using a very old version of odgi. Lots of thing are changed  (improved)!

Therefore, first of all, I would suggest to update your `odgi` to the current 0.5.1 version (also the current master would be fine though). However, it will change a bit your commands.

Regarding the graph conversion and sorting, the command that I would try is the following:

```
odgi build -g Hirundo.gfa -o - -P -t 32 | odgi sort --t 32 -i - -o Hirundo_sorted.og -p Y
```

Note the capital P in `odgi build`, and the `-t 32` parameter, because `odgi build` works in parallel now.

Moreover, with `-p Y` I am specifying to use the last sorting algorithm we developed. That is a path guided algorithm, which works very well in our cases. Give it a try! You could also try `-p Ygs` as sorting pipeline (path guided algorithm, grooming step to resolve spurious inverting links, and a topological sort).

Finally, for the visualization, the new `odgi viz` displays the path names on the left. Here an example image:

![image](https://user-images.githubusercontent.com/62253982/110981714-db5b5c80-8367-11eb-8d99-1755dec7ee84.png)

For more information on the path name visualization, take a look at #180.

Moreover, to explore better your graph, you could color the paths by prefix, using the `-s[C], --color-by-prefix=[C]` option. For example:

```odgi build -g two_strains.gfa -o - | odgi viz -i - -o two_strains.s.png -s '#'```

![image](https://user-images.githubusercontent.com/62253982/110981783-f332e080-8367-11eb-80cf-d996431dc800.png)

For more information and examples on this coloring feature, take a look at #191.

**Comment by AndreaGuarracino** [comment]
One last thing. The old `odgi viz` you are using is packing the graphs rather than displaying a single path per row by default. The current `odgi viz`, instead, displays a single path per row by default. Therefore, to pack the paths, you have to explicit that specifying `-R` in your `odgi viz` command line.

**Comment by SimonaSecomandi** [comment]
Hi Andrea,

many thanks!! I'll try tomorrow all the steps.

I'm facing some difficulties in installing the latest release. Currently, I'm using the conda version since it was easier to install.

I downloaded the latest tar.gz archive and unpack it and then I don't know what command to run for building it (I'm not an expert in building programs and I don't have root privileges, therefore I usually prefer to use conda).. 

I also tryied with this: 
git clone --recursive https://github.com/vgteam/odgi.git
cd odgi
cmake -H. -Bbuild && cmake --build build -- -j 3

But if failed (error in attached).. Sorry for the naive questions..

[error cmake git clone.txt](https://github.com/vgteam/odgi/files/6132293/error.cmake.git.clone.txt)

**Comment by AndreaGuarracino** [comment]
The compiler version is also quite old, I would suggest updating it to version 10.1 (9.3.0 might work too, but we can't guarantee that everything will work properly).

The conda issue is still a sore point. A Bioconda package of `odgi` can't be build, because conda comes with its own GCC V7.5. However, we are working to solve this problem soon somehow (see [https://github.com/bioconda/bioconda-recipes/pull/26189#issuecomment-767123749](https://github.com/bioconda/bioconda-recipes/pull/26189#issuecomment-767123749)).

**Comment by subwaystation** [comment]
If you have docker installed, you can use the docker image from the pggb pipeline https://github.com/orgs/pangenome/packages/container/package/pggb. Taking a look at https://github.com/pangenome/pggb#installation, just replace the pggb command with your odgi command of choice.

**Comment by SimonaSecomandi** [comment]
Hi all, many thanks for your help! I'm using the docker image and I ran the command you suggested (odgi build -g Hirundo.gfa -o - -P -t 32 | odgi sort -t 32 -i - -o Hirundo_sorted.og -p Y). However, even with 32 threads, it has been running for almost two days.. is it a common behaviour?

**Comment by AndreaGuarracino** [comment]
It depends on your input, but it seems too much! Try to put `-P` also in the `odgi sort` command

```
odgi build -g Hirundo.gfa -o - -P -t 32 | odgi sort -t 32 -i - -o Hirundo_sorted.og -p Y -P
```

This will show you a log and an estimate of the remaining time.

**Comment by SimonaSecomandi** [comment]
Ok, maybe it was stucked for two days. The log says:

[odgi::gfa_to_handle] building nodes: 100.00% @ 1.23e+06/s elapsed: 00:00:01:11 remain: 00:00:00:00
[odgi::gfa_to_handle] building edges: 100.00% @ 8.12e+05/s elapsed: 00:00:02:28 remain: 00:00:00:001
[odgi::gfa_to_handle] building paths: 100.00% @ 8.66e+01/s elapsed: 00:00:01:24 remain: 00:00:00:00
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

**Comment by subwaystation** [comment]
This usually means that you don't have enough memory to build the graph. How large is the GFA and how much RAM does your machine have?

**Comment by SimonaSecomandi** [comment]
The GFA is 10 Gbp.. I have 250 GB RAM, but I can try with a fat node with 1TB RAM!

**Comment by subwaystation** [comment]
Yes, 256GB RAM should be more than sufficient for such a file. 
Can you run [GDB](https://www.gnu.org/software/gdb/) on your system, to produce a backtrace?
Alternatively, is there a possibility for you to share the GFA? Or try to take a subset of it and identify the problem?
Thanks!

**Comment by SimonaSecomandi** [comment]
Ok I can try use GDB (never used before)! 

I just tried to run the exact same odgi command using the docker image, it is stucked here:

[odgi::gfa_to_handle] building nodes: 100.00% @ 1.53e+06/s elapsed: 00:00:00:56 remain: 00:00:00:00
[odgi::gfa_to_handle] building edges: 100.00% @ 1.07e+06/s elapsed: 00:00:01:51 remain: 00:00:00:000
[odgi::gfa_to_handle] building paths: 100.00% @ 8.48e+01/s elapsed: 00:00:01:26 remain: 00:00:00:00

But it doesn't return any error, it is still running without giving any information

**Comment by subwaystation** [comment]
You could try `gdb odgi`.
In GDB itself type `run build YOUR_ARGUMENTS`. Once it stops with an error, just type `bt` and you should see the full backtrace.

Hmm. Could also be, that there is one large path remaining to be build. Please wait some more time for it to finish.

**Comment by SimonaSecomandi** [comment]
I ran `gdb odgi` and then `run build -g Hirundo.gfa -o - -P -t 32 | odgi sort -t 32 -i - -o Hirundo_sorted.og -p Y -P` 

This is what it returned:

Starting program: /gpfs/home/projects/Hirundo/bin/odgi/bin/odgi build -g Hirundo.gfa -o - -P -t 32 | odgi sort -t 32 -i - -o Hirundo_sorted.og -p Y -P
[odgi::gfa_to_handle] building nodes: 100.00% @ 1.24e+06/s elapsed: 00:00:01:10 remain: 00:00:00:00
[odgi::gfa_to_handle] building edges: 100.00% @ 8.32e+05/s elapsed: 00:00:02:24 remain: 00:00:00:004
[odgi::gfa_to_handle] building paths: 100.00% @ 7.93e+01/s elapsed: 00:00:01:32 remain: 00:00:00:00
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
/bin/bash: line 1: 26244 Broken pipe             exec /gpfs/home/projects/Hirundo/bin/odgi/bin/odgi build -g Hirundo.gfa -o - -P -t 32
     26245 Aborted                 (core dumped) | odgi sort -t 32 -i - -o Hirundo_sorted.og -p Y -P
During startup program exited with code 134.

**Comment by subwaystation** [comment]
Please just try `run build -g Hirundo.gfa -o Hirundo.gfa.og -P -t 32` in `gdb` to catch the error of the `odgi build` command.

**Comment by SimonaSecomandi** [comment]
It actually created the output file very quickly, even if there were some warnings!!

(gdb) run build -g Hirundo.gfa -o Hirundo.gfa.og -P -t 32
Starting program: /gpfs/home/projects/Hirundo/bin/odgi/bin/odgi build -g Hirundo.gfa -o Hirundo.gfa.og -P -t 32
warning: File "/gpfs/software/Spack/opt/spack/linux-centos7-broadwell/gcc-8.4.0/gcc-10.1.0-bkxzvgr266virmwolahrmzujimk4ebod/lib64/libstdc++.so.6.0.28-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /gpfs/software/Spack/opt/spack/linux-centos7-broadwell/gcc-8.4.0/gcc-10.1.0-bkxzvgr266virmwolahrmzujimk4ebod/lib64/libstdc++.so.6.0.28-gdb.py
line to your configuration file "/home/users/simona.secomandi/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/home/users/simona.secomandi/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7f363c576700 (LWP 2254)]
[Thread 0x7f363c576700 (LWP 2254) exited]
[New Thread 0x7f363c576700 (LWP 2511)]
[odgi::gfa_to_handle] building nodes: 99.79% @ 1.39e+06/s elapsed: 00:00:01:02 remain: 00:00:00:00[Thread 0x7f363c576700 (LWP 2511) exited]
[odgi::gfa_to_handle] building nodes: 100.00% @ 1.23e+06/s elapsed: 00:00:01:10 remain: 00:00:00:00
[New Thread 0x7f363c576700 (LWP 2712)]
[odgi::gfa_to_handle] building edges: 100.00[Thread 0x7f363c576700 (LWP 2712) exited]: 00:00:00:0013
% @ 8.31e+05/s elapsed: 00:00:02:24 remain: 00:00:00:00
[New Thread 0x7f363c576700 (LWP 3350)]
[New Thread 0x7f363bd75700 (LWP 3351)]
[New Thread 0x7f363b574700 (LWP 3352)]
[New Thread 0x7f363ad73700 (LWP 3353)]
[New Thread 0x7f363a572700 (LWP 3354)]
[New Thread 0x7f3639d71700 (LWP 3355)]
[New Thread 0x7f3639570700 (LWP 3356)]
[New Thread 0x7f3638d6f700 (LWP 3357)]
[New Thread 0x7f363856e700 (LWP 3359)]
[New Thread 0x7f3637d6d700 (LWP 3360)]
[New Thread 0x7f363756c700 (LWP 3361)]
[New Thread 0x7f3636d6b700 (LWP 3362)]
[New Thread 0x7f363656a700 (LWP 3363)]
[New Thread 0x7f3635d69700 (LWP 3364)]
[New Thread 0x7f3635568700 (LWP 3365)]
[New Thread 0x7f3634d67700 (LWP 3366)]
[New Thread 0x7f3634566700 (LWP 3367)]
[New Thread 0x7f3633d65700 (LWP 3368)]
[New Thread 0x7f3633564700 (LWP 3369)]
[New Thread 0x7f3632d63700 (LWP 3370)]
[New Thread 0x7f3632562700 (LWP 3371)]
[New Thread 0x7f3631d61700 (LWP 3372)]
[New Thread 0x7f3631560700 (LWP 3373)]
[New Thread 0x7f3630d5f700 (LWP 3374)]
[New Thread 0x7f363055e700 (LWP 3375)]
[New Thread 0x7f362fd5d700 (LWP 3376)]
[New Thread 0x7f362f55c700 (LWP 3377)]
[New Thread 0x7f362ed5b700 (LWP 3378)]
[New Thread 0x7f362e55a700 (LWP 3379)]
[New Thread 0x7f362dd59700 (LWP 3380)]
[New Thread 0x7f362d558700 (LWP 3381)]
[New Thread 0x7f362cd57700 (LWP 3382)]
[New Thread 0x7f362c556700 (LWP 3383)]
[odgi::gfa_to_handle] building paths: 99.99% @ 8.49e+01/s elapsed: 00:00:01:26 remain: 00:00:00:00[Thread 0x7f363c576700 (LWP 3350) exited]
[Thread 0x7f362c556700 (LWP 3383) exited]
[Thread 0x7f362cd57700 (LWP 3382) exited]
[Thread 0x7f362d558700 (LWP 3381) exited]
[Thread 0x7f362dd59700 (LWP 3380) exited]
[Thread 0x7f362e55a700 (LWP 3379) exited]
[Thread 0x7f362ed5b700 (LWP 3378) exited]
[Thread 0x7f362f55c700 (LWP 3377) exited]
[Thread 0x7f362fd5d700 (LWP 3376) exited]
[Thread 0x7f363055e700 (LWP 3375) exited]
[Thread 0x7f3630d5f700 (LWP 3374) exited]
[Thread 0x7f3631560700 (LWP 3373) exited]
[Thread 0x7f3631d61700 (LWP 3372) exited]
[Thread 0x7f3632562700 (LWP 3371) exited]
[Thread 0x7f3632d63700 (LWP 3370) exited]
[Thread 0x7f3633564700 (LWP 3369) exited]
[Thread 0x7f3633d65700 (LWP 3368) exited]
[Thread 0x7f3634566700 (LWP 3367) exited]
[Thread 0x7f3634d67700 (LWP 3366) exited]
[Thread 0x7f3635d69700 (LWP 3364) exited]
[Thread 0x7f363656a700 (LWP 3363) exited]
[Thread 0x7f3636d6b700 (LWP 3362) exited]
[Thread 0x7f363756c700 (LWP 3361) exited]
[Thread 0x7f3637d6d700 (LWP 3360) exited]
[Thread 0x7f363856e700 (LWP 3359) exited]
[Thread 0x7f3638d6f700 (LWP 3357) exited]
[Thread 0x7f3639570700 (LWP 3356) exited]
[Thread 0x7f3639d71700 (LWP 3355) exited]
[Thread 0x7f363a572700 (LWP 3354) exited]
[Thread 0x7f363ad73700 (LWP 3353) exited]
[Thread 0x7f363b574700 (LWP 3352) exited]
[Thread 0x7f363bd75700 (LWP 3351) exited]
[Thread 0x7f3635568700 (LWP 3365) exited]
[odgi::gfa_to_handle] building paths: 100.00% @ 8.08e+01/s elapsed: 00:00:01:30 remain: 00:00:00:00
--Type <RET> for more, q to quit, c to continue without paging-- bt
[Inferior 1 (process 2250) exited normally]

**Comment by subwaystation** [comment]
It says ` [Inferior 1 (process 2250) exited normally]`. So it should have worked?

**Comment by subwaystation** [comment]
Maybe `odgi sort` was the problem.
You could find out with `run sort -t 32 -i Hirundo.gfa.og -o Hirundo_sorted.og -p Y -P`.

**Comment by SimonaSecomandi** [comment]
I thinks so! I typed `tb` when it asked "--Type for more, q to quit, c to continue without paging--" and this is what it said.

I'm now running `run sort -t -i Hirundo.gfa.og -o Hirundo_sorted.gfa.og -p Y -P -t 32` and for now (after around half an hour) it is working! I will let you know as soon as it finished! Maybe the problem was the concatenation of the two commands?

**Comment by subwaystation** [comment]
Glad it's working so far!

I am also wondering, what could have been the issue here. I just tried the concatenation as suggested in https://github.com/vgteam/odgi/issues/228#issuecomment-800910183 with a tiny graph. It worked for me.

**Comment by SimonaSecomandi** [comment]
I don't really know. I will try again with the concatenated command as soon as the sorting finish!!

**Comment by SimonaSecomandi** [comment]
So, the sorting worked well! I tried again with the concatenated command and it returned to me the same error (core dumped etc)

Now I'm a bit confused on what parameters to use with odgi viz.. 

I sorted the gfa with `odgi sort -t 32 -i Hirundo.gfa.og -o Hirundo_sorted.gfa.og -p Y -P` and then visualized it with `odgi viz -i Hirundo_sorted.gfa.og -o Hirundo_sorted.gfa.og.png.

However, the final imagine is enormous and the chromosomes of the reference are not showed!! I have 39 chromosmes in the reference and then a lot of unplaced scaffolds, while in the other genomes I have only set of contigs. I tried with the -p option to show only the 37 chromosomes from the reference (hoping that the png would show those 37 and all the aligned sequences) but it said that "no paths were found".. I know that these paths are present in the gfa since i retrieve the path names from there..

Here is the command:
`odgi viz -i Hirundo_sorted.gfa.og -o Hirundo_sorted_paths.png -p path_to_show.sh`
Here's the output:
[odgi::viz] Found 0/0 paths to display.
[odgi::viz] error: no path to display.

Here is the png from the first odgi viz command (i can remove it later if it is too big to show):

![Hirundo_sorted gfa og](https://user-images.githubusercontent.com/45236153/111484432-0c57da80-8736-11eb-825d-c2a4a51bf23f.png)

`

**Comment by AndreaGuarracino** [comment]
The old odgi viz you were using was packing the graph rather than displaying a single path per row by default. Instead, the current odgi viz displays a single path per row by default, that's why now your image is huge. To pack the paths, you have to explicit that specifying `-R` in your odgi viz command line.

```
odgi viz -i Hirundo_sorted.gfa.og -o Hirundo_sorted.gfa.og.png -R
```

However, in such a mode, you will lose the path names on the left in the visualization.

With the `-p` option you can specify a subset of the paths to visualize. To have a list of the paths present in the graph, you can use

```
odgi paths -i Hirundo_sorted.gfa.og -L > paths.txt 
```

From that list, you can leave only the paths that you would like to visualize with `odgi viz ... -p paths.txt`.

**Comment by SimonaSecomandi** [comment]
I'm using the current odgi version of course, but I need the path names.. I need at least the big chromosomes from my reference (it's a bird, so we have Mbp long chr) and all the aligned sequences from the other 5 genomes.. I would expect something like the big chr sequence and below it all the aligned sequences (contigs) from the other individuals, since my goal is to visualize the sinteny and differences between individuals.. with the -p option, specifying only the reference chr, I can't see what contigs from the other individuals have been aligned to them.. 

Here's is the png from odgi viz -i Hirundo_sorted.gfa.og -o Hirundo_sorted_paths.png -p paths.txt (I tried also with -p and -R but the program said that only one can be specified)

![Hirundo_sorted_paths](https://user-images.githubusercontent.com/45236153/111490495-5c856b80-873b-11eb-80db-3c5ccabed1cf.png)

Do you have any suggestions on how to generate something like that? So, the chromosomes and below it all the aligned sequences from the other individuals..





![Hirundo_sorted_paths](https://user-images.githubusercontent.com/45236153/111489991-ef71d600-873a-11eb-99c7-4229501f28bc.png)

**Comment by subwaystation** [comment]
If you are interested in one chromosome only, `-r[STRING],--pangenomic-range=[STRING]` could help you here. You can identify the pangenome start and end position with `odgi position`. Feeding these into `odgi viz`, the visualization will specifically focus on the desired pangenome subregion, in your case the chromosome of choice.

**Comment by SimonaSecomandi** [comment]
@AndreaGuarracino yes I know about the possibility to order them.. but I don't know which contigs aligns to which chromosomes.. by doing like you said, so if I change the orders of my paths or just display some of them, I am looking at the alignment between the selected paths or not? That's what I can't understand.. 
In the last image I posted, for example, I showed the main chromosomes (e.g. bHirRus1.SUPER_1) and the unloc_scaffolds that belongs to a certain chromosome (e.g. bHirRus1.SUPER_21_unloc_*) of the individual called bHirRus1 (the reference), but these were not the alignments between them, that's right? So I can't understand how can I display the alignment between a reference chr ad the aligned sequences..

@subwaystation I tried with `odgi position -i Hirundo_sorted.gfa.og -r bHirRus1.SUPER_1 -t 32` but is not returning me anything.. on the manual it's said that an exit status 0 means success, but I was expecting some coordinated to be feeded into odgi viz! I can try again tomorrow..

**Comment by ekg** [comment]
Why not use approximate mapping to partition your contigs by chromosome? Do
you expect a lot of rearrangement?

**Comment by AndreaGuarracino** [comment]
If I understand correctly, you are interested in starting from a reference chromosome and seeing in that portion of the graph the other things that align with it. If it is just visualization and you are only working with the smoothed graph (not also the consensus graphs), then you don't need `odgi position`. With `odgi viz` you can visualize a 'vertical' portion of the graph, specifying directly a path range (a reference one usually):

`odgi viz -i Hirundo_sorted.gfa.og -o Hirundo_sorted_paths.png -r 'bHirRus1.SUPER_1:xxxx-yyyy'`

with `xxxx` and `yyyy`, the start and end coordinates of your range, respectively.

[Here an example](https://github.com/vgteam/odgi/pull/214#issuecomment-781669920) to visualize human centromeres.


In case you will be interested (perhaps for subsequent analyzes) to literally extract a portion of the graph, creating a subgraph, I report here also the fresh `odgi extract` command, recently implemented.

`odgi extract -i Hirundo_sorted.gfa.og -o Hirundo_sorted_paths.og -r 'bHirRus1.SUPER_1:xxxx-yyyy' --full-range`

**Comment by SimonaSecomandi** [comment]
@ekg Hi! What do you mean with "approximate mapping"? Here I'm just trying to create a preliminary pangenome for the Barn swallow, and I'm looking for ways to visualize it, since I need a picture for the paper I'm writing! So I believe that having all the chromosomes from the reference and the respective aligned contigs from the other individuals would be great. I Don't think there will be lots of rearangements since we are talking about individuals from the same species, but when creating the pangenome with the Cactus pipeline, it said that has incorporated some inversions, for example! I would like to visualize some of them if possile.

@AndreaGuarracino many thanks Andrea, I'll try it wight now! Where can i retrieve the range information for my chromosome?
An by doing this (`odgi viz` or `odgi extract` with range specified) I can get also all the aligned contigs to that chr?

As I said above, I would like an image to show in my paper and I throught that it would have all the chromosomes for my reference (39) in horizontal, and all the aligned contigs below them, rather than focus on a single chromosome. Isn't that possible? Maybe with a different sorting command? The last output picture i poster is just very big in height and I can't see the big chromosomes, which are the biggest sequences in the graph, while the contigs from the other individuals are much smaller.. An horizontal image like the ones you show in your examples, would be much better to visualize possible rearrangements, rather than have all the paths stacked (like in my big image).. but I don't know if it possible.. many thanks for you help again!! The Cactus pipeline for generating a pangenome was released last months and I never worked with variation graphs, so I'm sorry if i seem a little naive with my questions..

**Comment by SimonaSecomandi** [comment]
Hi @AndreaGuarracino, I tried to extract the range of my chromosome 1 for `odgi extract` or `odgi viz` , but I don't know which is the best command to to that. 

I tried with: 
`odgi position -i Hirundo_sorted.gfa.og -r bHirRus1.SUPER_1 -t 32` but it returned no output
`odgi panpos -i Hirundo_sorted.gfa.og.xp -p bHirRus1.SUPER_1` but requires also a nucleotide position that I didn't understand

Moreover, about the initial sorting, do you think that `-p Y` or `-p Ygs` are enough or do you recommand other sorting options? 

Many thanks!

**Comment by AndreaGuarracino** [comment]
Which problem did you have with the following commands?

```
odgi viz -i Hirundo_sorted.gfa.og -o Hirundo_sorted_paths.png -r 'bHirRus1.SUPER_1:xxxx-yyyy'
```

```
odgi extract -i Hirundo_sorted.gfa.og -o Hirundo_sorted_paths.og -r 'bHirRus1.SUPER_1:xxxx-yyyy' --full-range
```

If you are interested in visualizing stuff regarding a chromosome, you can just use `odgi viz`, specifying as range 0-length_of_your_chromosome.

Regarding the sorting, we apply `-p Ygs` and it is usually enough.

**Comment by SimonaSecomandi** [comment]
I thought that I had to use the range of my chromosome inside the pangenome and not the length of my genome! That's good.

However, both commands returned this error (evaluated with gdb):

(gdb) `run viz -i Hirundo_sorted.gfa.og -o Hirundo_sorted_paths.png -r 'bHirRus1.SUPER_1:0-156035725'`
Starting program: /gpfs/home/projects/Hirundo/bin/odgi/bin/odgi viz -i Hirundo_sorted.gfa.og -o Hirundo_sorted_paths.png -r 'bHirRus1.SUPER_1:1-156035725'
warning: File "/gpfs/software/Spack/opt/spack/linux-centos7-broadwell/gcc-8.4.0/gcc-10.1.0-bkxzvgr266virmwolahrmzujimk4ebod/lib64/libstdc++.so.6.0.28-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
warning [libhandlegraph]: Serialized handle graph does not appear to match deserialzation type.
warning [libhandlegraph]: It is either an old version or in the wrong format.
warning [libhandlegraph]: Attempting to load it anyway. Future releases will reject it!
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error rewinding to load non-magic-prefixed SerializableHandleGraph
Program received signal SIGABRT, Aborted.
0x00007f24cb7e9387 in raise () from /lib64/libc.so.6

(gdb) `run extract -i Hirundo_sorted.gfa.og -o Hirundo_sorted_paths.og -r 'bHirRus1.SUPER_1:0-156035725' --full-range`
Starting program: /gpfs/home/projects/Hirundo/bin/odgi/bin/odgi extract -i Hirundo_sorted.gfa.og -o Hirundo_sorted_paths.og -r 'bHirRus1.SUPER_1:0-156035725' --full-range
warning: File "/gpfs/software/Spack/opt/spack/linux-centos7-broadwell/gcc-8.4.0/gcc-10.1.0-bkxzvgr266virmwolahrmzujimk4ebod/lib64/libstdc++.so.6.0.28-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
warning [libhandlegraph]: Serialized handle graph does not appear to match deserialzation type.
warning [libhandlegraph]: It is either an old version or in the wrong format.
warning [libhandlegraph]: Attempting to load it anyway. Future releases will reject it!
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error rewinding to load non-magic-prefixed SerializableHandleGraph
Program received signal SIGABRT, Aborted.
0x00007fd1dc935387 in raise () from /lib64/libc.so.6

**Comment by SimonaSecomandi** [comment]
I Just manage to run `/home/users/simona.secomandi/Hirundo/bin/odgi/bin/odgi viz -i Hirundo_pangenome_sorted_Ygs.og -o Hirundo_pangenome_sorted_Ygs_viz.png -r 'bHirRus1.Chr1:1-156035725'`, while odgi extract keep returning me that error.

However, the `odgi viz` image is similar to the last I posted here (it's very big in height and didn't show only my chromosome 1 and all aligned to it, it shows everything in randomic order..)

**Comment by SimonaSecomandi** [comment]
Hello, I'm sorry for bothering you. I believe that my only chance to have a compact image is to display only the sequence of interest. A problem occurs when trying to visualize my paths (I tried with only two paths).

`odgi viz -i Hirundo_pangenome_sorted_Ygs.og -o Hirundo_pangenome_sorted_Ygs_viz_Chr3_paths.png -p paths_Chr3_A1.txt -x 3000`
[odgi::viz] Found 1/2 paths to display.

It only found the Chromosome 3 but not the other path. 

This is the content of paths_Chr3_A1.txt:
bHirRus1.Chr3
HrA1.A1_contig1

I veryfied these are the correct names by looking at: 
odgi paths -t 32 -i Hirundo_pangenome.vg.gfa.og -L > ALL_paths.txt 

Maybe the txt file with the paths of choice has to be formatted in a different way?

**Comment by AndreaGuarracino** [comment]
Hi Simona, the file with the selected paths has to have 1 path name per row. Assuming `Hirundo_pangenome_sorted_Ygs.og` and `Hirundo_pangenome.vg.gfa.og` contain the same paths, your commands look right. 

To help you a little better, it would be helpful if you could also share some small parts of your data showing such problems. You could replace real sequences with dummy sequences if you have sharing problems. Do you think it is feasible?

**Comment by SimonaSecomandi** [comment]
Hi Andrea, yes the path names were the same. I now made odgi viz work with an .og file extracted with `odgi extract` on cromosome 3. I visualized only the chr3 and two contigs that align against it (I retrieve the information by aligning the two assemblies with minimap2). And it found the three paths and made the image (below)!! I don't know why it didn't worked with the entire graph..

![bHirRus1 Chr3%3A0-116801624_paths](https://user-images.githubusercontent.com/45236153/112726687-0bd1f780-8f1f-11eb-80db-eba1815719e9.png)


However, I was trying the same with another Chr agains which some of the other assemblies have an inversion (according to Minimap2). `odgi viz` found the paths but it failed with: Segmentation fault (core dumped).

`odgi viz -i bHirRus1.Chr6:0-63258488.og -o Chr6_inversion_paths.png -p paths_Chr6_inversion.txt`

Finally, I will try to shared some parts of the graph, maybe extracting it on the range of a little scaffold/contig?

**Comment by AndreaGuarracino** [comment]
Yes @SimonaSecomandi, a little part that leads to your problem. This would be the way to help you as soon as possible.

**Comment by subwaystation** [comment]
@SimonaSecomandi Are there still some open questions? Else I would close this :)

**Comment by SimonaSecomandi** [comment]
You can close it, thank you :)
