### ISSUE TITLE
Installation problem with GOMP_parallel

### ISSUE THREAD

**Issue by evolgen** [pangenome/odgi#35]
Hi Erik,

I was trying to get odgi installed but run into problems with GOMP_parallel.

Exactly at the following step -
[ 75%] Linking CXX executable /global/scratch2/Software/odgi/build/bsort-prefix/src/bsort/bin/bsort
/global/scratch/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /global/scratch2/Software/odgi/build/bsort-prefix/src/bsort/lib/libbsort.a(bsort.cpp.o): in function `bsort::radixify(unsigned char*, long, long, long, long, long, long, long, long, long)':
bsort.cpp:(.text+0xc2b): undefined reference to `GOMP_parallel'

It's the same problem with seqwish too. I have conda installations of gcc, boost (xgboost) and openmp. Can you please let me know what I am missing here?

Cheers,
Rohit

**Comment by ekg** [comment]
What does uname -a return? (What's the OS?)

You shouldn't need xgboost. That's a machine learning library and not used
at all. Not is boost used.

You may need to use gcc to compile this. The error is related to OMP, and
the support for this is apparently still different between clang and gcc.

**Comment by evolgen** [comment]
Its Fedora linux, uname -a returns
Linux ln003.brc 3.10.0-693.11.6.el7.x86_64 #1 SMP Wed Jan 3 18:09:42 CST 2018 x86_64 x86_64 x86_64 GNU/Linux

gcc, boost and zlib were loaded in my environment by default

**Comment by ekg** [comment]
I suspect the problem is a mismatch between conda libraries and those on
the system. For a regular Linux system with gcc and cmake and zlib I don't
think you need to install anything else. Let's see. Take the conda
libraries out of your environment and try the build again.

**Comment by evolgen** [comment]
I created a new environment for seqwish instead with gcc, zlib and cmake (since the default environment contains too much crap). This environment has problems detecting cmake and zlib library paths weirdly. After resolving it, the GOMP_parallel still persists. Are there binaries available for odgi?

**Comment by evolgen** [comment]
I had to change to the bsort folder, download the version as given in that readme file, compile it manually using reconf and it compiled. However, while returning to the main installation, the omp installation error reappears - 
cannot find -lgomp
collect2: error: ld returned 1 exit status
gmake[2]: *** [../bin/odgi] Error 1
gmake[1]: *** [CMakeFiles/odgi.dir/all] Error 2

Since there is an installed openmp through conda, reinstalling conda is the only solution I can think of. Thanks for the help.

**Comment by ekg** [comment]
I have just figured out the problem. It is the lack of static libraries for
openmp and libatomic that will cause this. The solution is to not compile
statically. I will parameterize this with a build variable. For the moment
you can remove the second to last line in the CMakeLists.txt to disable the
static build.

**Comment by evolgen** [comment]
Excellent!
I have an update regarding the my installation problem too (without conda reinstallation). Conda had problems detecting the libraries, hence I had to add libgomp installation from gcc-9.1.0, which in-turn needed installation of gmp-6.1.2, isl-0.21, mpc-1.1.0, mpfr-4.0.2. This worked for the odgi installation :)

**Comment by ekg** [comment]
I am using junest to compile seqwish and odgi, with (bleeding edge stuff
like GCC 9.1.0) from the Arch Linux distribution. There is an apparent
performance penalty from the proot environment, but it is letting me run a
full build environment without docker or root.

I haven't been able to build odgi yet in that environment for other reasons
than the static build. I'm thinking of reducing it's dependency footprint.
(The problem for me is in sonLib, which is only being used for some
experimental stuff.)
