### ISSUE TITLE
sort the path name by a input file

### ISSUE THREAD

**Issue by baozg** [pangenome/odgi#354]
Can we define the order of the path in a file for `odgi viz`? (To group the SV type or to group by subpopulation)

**Comment by AndreaGuarracino** [comment]
In `odgi viz` you can use

```
      [ Path Selection Options ]
        -p[FILE],
        --paths-to-display=[FILE]         List of paths to display in the
                                          specified order; the file must contain
                                          one path name per line and a subset of
                                          all paths can be specified.
```

The paths displayed will follow the order specified in the file.

**Comment by baozg** [comment]
Thanks. Can we color the path name with a defined csv (like `Bandage` load csv) ? Can `odgi` output vector images (pdf or svg) or high resolution png ?

**Comment by AndreaGuarracino** [comment]
Unfortunately, both of such features are not supported. You can mitigate the first one by using
```
        -s[CHAR],
        --color-by-prefix=[CHAR]          Color paths by their names looking at
                                          the prefix before the given character
                                          CHAR.
```
and the second one by trying to convert the PNG to a PDF, or requesting bigger PNGs (bigger `-x` and `-y` values).
