### ISSUE TITLE
terminate called after throwing an instance of 'std::bad_alloc'   what():  std::bad_alloc

### ISSUE THREAD

**Issue by shengwang** [pangenome/odgi#357]
both bioconda (odgi-0.6.2) and docker (odgi:0.6.2--py38h8e3bb3f_0) version throw an exception when calling odgi subcommand

warning [libhandlegraph]: Serialized object does not appear to match deserialzation type.
warning [libhandlegraph]: It is either an old version or in the wrong format.
warning [libhandlegraph]: Attempting to load it anyway. Future releases will reject it!
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

**Comment by ekg** [comment]
Do you have a test case we could use to reproduce this problem?

**Comment by subwaystation** [comment]
@shengwang Any updates?

**Comment by subwaystation** [comment]
Seems like it is not an issue anymore. Else, please re-open.
