### ISSUE TITLE
Can we use odgi to analyze graphs made from assemblers

### ISSUE THREAD

**Issue by hwalinga** [pangenome/odgi#36]
I was wondering if we could also use odgi to analyze graphs made by assemblers. So far it seems that it can only handle files made by seqwish as `odgi build` throws the following error if I give it something else: 

```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stol
Aborted (core dumped)
```

**Comment by ekg** [comment]
You have to convert the GFA to vg-GFA format, which is a restricted subset
of GFAv1. There are only two things that matter. The essential one is that
node IDs are positive integers. You can probably write a script to correct
this. This is what is causing the error you're encountering. The other
element of vg-GFA format is that there are no edge overlaps, but this won't
break your use of odgi.

**Comment by hwalinga** [comment]
We have a different error now :

```
node 0
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 9223372036854775807) >= this->size() (which is 17)
Aborted (core dumped)
```

strace included:  

https://termbin.com/hihs

**Comment by ekg** [comment]
It should be fine if you have positive non-zero integers.

**Comment by hwalinga** [comment]
The problem was indeed the zero. However, the resulting file dg file cannot be sorted: 

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 144) >= this->size() (which is 17)
Aborted (core dumped)
```

**Comment by ekg** [comment]
I ran into something similar yesterday. Is your graph small / can you share
it here?

**Comment by hwalinga** [comment]
Yes, I emailed you on the email address linked to your github account (gmail).

**Comment by ekg** [comment]
Hi, I'm sorry to have let this drop. The good news is that I have a new pipeline for importing assembly graphs into odgi.

The idea is illustrated on the [gimbricate](/10.1093/bioinformatics/btr655) readme, specifically here https://github.com/ekg/gimbricate#pangenome-construction

**Comment by subwaystation** [comment]
Seems like this is solved.
