### ISSUE TITLE
odgi extraction and 

### ISSUE THREAD

**Issue by code-acc** [pangenome/odgi#367]
Hello!

I want to extract red boxed region from the pangenome graph (image 1) and build a new graph. With odgi extract command,  I can extract the region, but each sequence gets truncated and realigned (image 1). Can the truncation be avoided? 
Image 1:
![image](https://user-images.githubusercontent.com/57204282/155375754-3433a732-be99-4b1f-84a9-b041cee2265a.png)

Image 2:
![image](https://user-images.githubusercontent.com/57204282/155375780-29263f43-94cb-4344-af2f-dc1332a89b76.png)

Another thing - How to change the graph colors from black to red and red to black? 

Thank you,
Minal

**Comment by subwaystation** [comment]
Hi @code-acc,

what `odgi extract` command did you execute? Did you include `-E` in your command?

Unfortunately, `odgi viz` does currently not support a different coloring scheme. 

Best,
Simon

**Comment by AndreaGuarracino** [comment]
We prefer not to allow too much freedom in color changes to be able to easily understand by eyes what each visualization is showing (coverage, stradness, etc...).

Also here, the topology of the graph is important to understand what is going on during the extraction.

**Comment by subwaystation** [comment]
Were we able to help you out @code-acc ?

**Comment by code-acc** [comment]
Hi @subwaystation and @AndreaGuarracino!

Sorry, it took me long to get back to this. I used the command with -E "odgi extract -i smooth.og -r chr6:21582765-26568581:600000-3385816 -E -o - | odgi viz -i - -o extract.png". 

For a temporary solution, I am using a cropped image now.

Thanks!

**Comment by subwaystation** [comment]
@code-acc Were you able to solve this for your satisfaction? Then I would close the issue ;)

**Comment by code-acc** [comment]
Hi @subwaystation! Yes! Thanks for helping :)
