### ISSUE TITLE
Optimasing odgi graphs

### ISSUE THREAD

**Issue by Chaima-Bouchenak** [pangenome/odgi#369]
Hello, 
can someone please explain to me what is this?
I know it compacts nodes IDs, but why is this important and what is does to the original graph ?
should i process in optimizing any .og file that I create during my analysis and how far that would change downstream stats.

Thank you in advance.

**Comment by AndreaGuarracino** [comment]
From the performance point of view, optimized graphs take up less memory thanks to the compaction of the IDs.

However, functionally, there are many ODGI's tools that require optimized graphs If the IDs are compacted, the nodes can be trivially mapped into a simple array. For example, if there are 100 nodes in the graph, with IDs from 0 to 99, those nodes can be mapped into an array of 100 elements by using their IDs. On the other hand, if the graph contains 100 nodes, with IDs ranging from 0 to 10000, you cannot simply use such IDs to map nodes without managing the non-contiguous ID space.

It's a simple trick, but it allows us to write more efficient tools.

**Comment by Chaima-Bouchenak** [comment]
> From the performance point of view, optimized graphs take up less memory thanks to the compaction of the IDs.
> 
> However, functionally, there are many ODGI's tools that require optimized graphs If the IDs are compacted, the nodes can be trivially mapped into a simple array. For example, if there are 100 nodes in the graph, with IDs from 0 to 99, those nodes can be mapped into an array of 100 elements by using their IDs. On the other hand, if the graph contains 100 nodes, with IDs ranging from 0 to 10000, you cannot simply use such IDs to map nodes without managing the non-contiguous ID space.
> 
> It's a simple trick, but it allows us to write more efficient tools.

Perfect, it's clear, thank you for the quick response @AndreaGuarracino
