### ISSUE TITLE
sort command ''killed''

### ISSUE THREAD

**Issue by Chaima-Bouchenak** [pangenome/odgi#370]
Hello, i'm trying to viz an odgi graph following this [tutorial](https://odgi.readthedocs.io/en/latest/rst/tutorials/remove_artifacts_and_complex_regions.html). It's recommended to sort it first and run the following command :
```
odgi sort -p Y -i pan.clean.exp.7.og -o pan.exp.7_opt.og -P
```
The task is *killed* and a new folder ''xp-******" is created containing the following files : 
- xp-ZaIWJJ  
- xp-ZaIWJJ.node_path.mm  
- xp-ZaIWJJ.pathnames.iv

Some graph infos : 
```
#length nodes   edges   paths
149070002       4044469 5601291 63634
```
any clarifications please?

**Comment by subwaystation** [comment]
How much RAM do you have available? How large is the graph file on disk?

**Comment by subwaystation** [comment]
The xp folders are temporary folders. Your way of running odgi sort invokes the PG-SGD algorithm which first needs to build a path index to work efficiently. I suspect you run out of RAM during that building process.

**Comment by subwaystation** [comment]
From the size of the file, that's hard to tell. Depends on the variation in the graph. My wild guess is that 16GB RAM should suffice.

Anyhow, it could be to little RAM, too little disk space, or a real bug. Would you be able to share the graph with me? Thanks!

**Comment by Chaima-Bouchenak** [comment]
@subwaystation , thanks as you mentioned it was due to a resource limitation. Scaling it up solved the problem
