### ISSUE TITLE
Graph depth

### ISSUE THREAD

**Issue by Chaima-Bouchenak** [pangenome/odgi#387]
Hello, 

**Context**
I have built a pangenome graph using VG, converted it into ODGI.
Now i want to have an overview of its complexity and remove the problematic regions. In order to do so, I followed this [tutoriel](https://odgi.readthedocs.io/en/latest/rst/tutorials/remove_artifacts_and_complex_regions.html).
```
odgi depth -i x.og -w 1000:0:1 > low_depth.bed
odgi depth -i x.og -w 1000:100:100000 > high_depth.bed
```
However, I am not able to detect any High depth regions (the file is empty) 
To check the depth, i run :
```
odgi depth -i mygraph.og
```
The results show me **depth means** going from **min *20,3* - max *20,7***.

Knowing that my graph contains 21 paths ( REF + 20 haplotypes/threads ), i think this has to do with the depth results.
Putting MAX at *21* (the -w arg), in this case, would be wrong as that would refer to an area where all paths pass, so common regions, which won't be ''complex'' then?!

How can i detect ''true'' complex regions ? 
Would be great to have further explanations about this topic.

Please don't hesitate to come back to me if any point from those mentioned above is not clear.

Best,
Chaima

**Comment by subwaystation** [comment]
Hi @Chaima-Bouchenak 

Did you built your graph with `vg construct` using a VCF? What is the organism you are looking at?
Were repeat regions in the reference of the VCF masked?

We use the complexity detection method for graphs built with https://github.com/pangenome/pggb. The input can be contigs, long reads, or whole chromosomal sequences. All of them are unmasked and therefore we will get a certain level of complexity when building e.g. a human pangenome graph.

I hope this helps.

Best,
Simon

**Comment by subwaystation** [comment]
Looks like this is not an issue anymore.
