### ISSUE TITLE
Exploring node size along paths

### ISSUE THREAD

**Issue by StefanReuscher** [pangenome/odgi#414]
Hi,

I was looking for a method to explore the node length (size in bp) in my graphs, but I couldnt find any option to do so in the odgi tools. Is there one ?

Then I tried using the python API to script it myself. When I run it step-by-step in an interactive python console it works for some graphs, but not for others. When I run that as a script, it always fails.

The error is always a segementation fault. My graphs all come from PGGB or subgraphs of those. Any idea why some work and some dont ?

Also, great work, keep it up !

**Comment by ekg** [comment]
You should never get a segfault. That's a problem! Would you please share a test graph and the script that causes the segfault?

What API would you suggest for exploring node size. This is something we have been talking about exposing more easily. In pggb graphs the node size relates to variation density, which is a very interesting biological metric. I think your intuition that this is interesting is right on.

**Comment by StefanReuscher** [comment]
I will try to compile an example file that fails with segfault later.

I could imagine that another odgi command would be most appreciated by the community. odgi nodesize could complement the existing odgi depth/degree commands. Something like odgi nodesize -i in.og -p pathname or region -o tab-separated file with columns nodeID and size. Thats what I tried to create.

Node size can be proxy for both variation density but also courseness of the graph along a path. I imagined that you might want different levels of detail granularity, depending on the use case. I started looking into this because the other metrics given by odgi stats (path node distance or mean link lenght) or not very intuitive for me. Actually, I dont get them all...

Here is my python script to extract node id and size, based on the example in the ReadThedocs:

```
import argparse
import numpy
import odgi

parser = argparse.ArgumentParser(description="extract the length of nodes from a path from a .og file")
parser.add_argument("-i", type=str, help="infile")
parser.add_argument("-o", type=str, help="outfile")
parser.add_argument("-p", type=str, help="pathname")
args = parser.parse_args()

gr.load(args.i)

path = gr.get_path_handle(args.p)
step = gr.path_begin(path)

node_id = []
node_length = []

while(gr.has_next_step(step)):

    current_node_handle = gr.get_handle_of_step(step)

    # ask the node handle for the ID and length
    node_id.append(gr.get_id(current_node_handle))
    node_length.append(gr.get_length(current_node_handle))

    # progress to the next step
    step = gr.get_next_step(step)


results = numpy.array([node_id, node_length], dtype = int)
results = numpy.transpose(results)
numpy.savetxt(args.o, results, fmt="%d")

```

**Comment by AndreaGuarracino** [comment]
As a quick answer, your need seems something very `awk`able by parsing the corresponding GFA output:

```
odgi view -i input.og -g | grep '^S' | awk -v OFS='\t' '{print($2,length($3))}'
```

- go from ODGI format to GFA format
- grep S lines
- print in a tab-separated manner node id and node length

**Comment by StefanReuscher** [comment]
Yes, I am looking at the GFA right now. I somehow got so focussed that I forgot about it yesterday.

**Comment by subwaystation** [comment]
Looks like this is not an issue anymore.
