### ISSUE TITLE
When will the new merge feature in extract be available via conda?

### ISSUE THREAD

**Issue by Yutang-ETH** [pangenome/odgi#423]
Hi,

I read this #419 and I am wondering when this could be available via conda installation?

By the way, I installed odgi via conda as told, but when I do odgi version -v, nothing is printed out.

Thank you very much.
Yutang

**Comment by AndreaGuarracino** [comment]
Have fun! https://anaconda.org/bioconda/odgi

Let us know if also this version doesn't print something with `odgi version`.

P.S.: it is very likely that `odgi extract` will get another power-up soon, to better solve the path fragmentation in the subgraphs. Stay tuned.
