### ISSUE TITLE
Problem with python module: steps_of_handle returns C object

### ISSUE THREAD

**Issue by susan-garry** [pangenome/odgi#424]
Using the `.so` files that I downloaded [here](https://anaconda.org/bioconda/odgi/files) from bioconda, I was able to successfully run `import odgi` in python scripts. However, when I try to run something like `for step in graph.odgi.steps_of_handle`, I receive the following error message:

![image](https://user-images.githubusercontent.com/24484834/175562841-2a5ea83c-c5a4-4dad-8cef-c3dc01384ab6.png)

This does not seem like exected behavior to me; I would have expected the function to return a python list. Obtaining a list of all steps on a handle can also be accomplished with the `graph.odgi.for_each_step_on_handle` method, but I don't know why someone would want the `std::vector` object.

On a slightly unrelated note, what does the second argument, `arg1`, represent? The error persists regardless of its value, but I am nonetheless curious since it is not specified in the documentation.

I am using the Python 3.8 version. Thank you!

**Comment by subwaystation** [comment]
Where you able to solve this @susan-garry? Maybe @pjotrp knows more?

**Comment by susan-garry** [comment]
Unfortunately, no; the same functionality as `steps_of_handle` can be accomplished with other methods, but `steps_of_handle` seems to be buggy despite being listed as a method in the [Python Bindings](https://odgi.readthedocs.io/en/latest/rst/binding/api.html) section of the documentation.

**Comment by pjotrp** [comment]
These Python bindings deserve a health warning. You may be the first one to try!

Also there are two versions of bindings. The documentation you refer to is the old type. I wrote another one at https://github.com/pangenome/odgi/blob/master/test/python/odgi_ffi.md that is significantly faster, but also not much production tested.

**Comment by pjotrp** [comment]
For the other question it probably is an idea to get acquainted with the underlying odgi code. https://github.com/pangenome/odgi/blob/484135459d6100cf7b69b3e479d9280d9567e082/src/odgi-api.cpp#L301 and https://github.com/pangenome/odgi/blob/484135459d6100cf7b69b3e479d9280d9567e082/src/odgi.cpp#L261. It is not hard to hack.

**Comment by susan-garry** [comment]
Ah, thank you! I've been using `https://odgi.readthedocs.io/` and I didn't notice anything about the new python bindings. Looks really interesting, I'll check it out!
