### ISSUE TITLE
Error when sorting the graph using -Y option

### ISSUE THREAD

**Issue by LiaOb21** [pangenome/odgi#430]
Dear developers, 
Thank you so much for this tool!

I created a pangenome of Arabidopsis following the minigraph-cactus pangenome pipeline. Then, I installed odgi using conda to visualise the pangenome graph. The output of the minigraph-cactus pipeline is a .gfa.gz file that was unizipped to create the .og file using the following command:

`odgi build -g Arabidopsis_pg/Arabidopsis_pg.gfa -o odgi/Arabidopsis_pg.og -t 20 -P -O`

I first tried to visualise the output as follows:

`odgi viz -i odgi/Arabidopsis_pg.og -o odgi/Arabidopsis_pg.png`

And this is the output:
![image](https://user-images.githubusercontent.com/96196229/178756137-fe456219-7582-4bfa-948e-f11024edc0c6.png)

Then, I tried to sort the graph, in order to see if a better visualisation is possible, but this is the error that I got using the -Y option for sorting:

`odgi sort -i odgi/Arabidopsis_pg.og -t 20 -P -Y -o odgi/Arabidopsis_pg_sorted.og 
odgi: /opt/conda/conda-bld/odgi_1657286605938/work/build/sdsl-lite-prefix/src/sdsl-lite-build/include/sdsl/int_vector.hpp:1360: sdsl::int_vector<<anonymous> >::reference sdsl::int_vector<<anonymous> >::operator[](const size_type&) [with unsigned char t_width = 1; sdsl::int_vector<<anonymous> >::reference = sdsl::int_vector_reference<sdsl::int_vector<1> >; sdsl::int_vector<<anonymous> >::size_type = long unsigned int]: Assertion `idx < this->size()' failed.
Aborted (core dumped)
`

When I try to randomly sort the graph (-r option), it works, but the output looks very strange:
`odgi sort -i odgi/Arabidopsis_pg.og -t 20 -O -P -r -o odgi/Arabidopsis_pg_random_sorted.og`
![image](https://user-images.githubusercontent.com/96196229/178756536-d034279c-e54a-444f-bcd9-5c2ecaf39473.png)

Do you have any idea about what can be the issue? Am I missing something in the steps to follow?

Thank you so much in advance for any help!

Cheers,

Lia

**Comment by subwaystation** [comment]
Dear @LiaOb21,

Thanks for trying out ODGI and applying it to a minigraph + cactus GFA. I am actually not sure where the error is coming from. Could be an actual bug or a conda issue. 
I would need a full traceback from a tool like gdb https://www.sourceware.org/gdb/.
It would be something like:

```
gdb odgi
run sort -i odgi/Arabidopsis_pg.og -t 20 -P -Y -o odgi/Arabidopsis_pg_sorted.og
```

Or would it be possible to somehow share the data?

Best,
Simon

**Comment by subwaystation** [comment]
Forgot to tell you to type `bt` in `gdb` after the program has finished. Then we will have the full traceback.
Could you please also try your command with the current ODGI docker image? Instructions are at https://github.com/pangenome/odgi#docker=.

Thanks!

**Comment by subwaystation** [comment]
Thanks!
Looks like during the path index construction something goes out of place. Could be, because of the libc.so.6. Or could be a bug.
It would be of great help, if you could share the data somehow. You can also drop an mail to simon.heumos@qbic.uni-tuebingen.de.

Curious, if the docker worked.

**Comment by ekg** [comment]
This would typically indicate some error in the path space or indexing of
it.

Can you share the graph?

Did you convert it into P-line format with gfa-wp?

**Comment by LiaOb21** [comment]
Hi @ekg,

I just dropped an email with my .gfa.gz file to Simon. Thank you so much!

**Comment by LiaOb21** [comment]
Hi @ekg and @subwaystation,

I am sorry, but I don't have really clear how to use gfa-wp.
I also tried to use vg convert, how it was suggested in another issue: 

`vg convert ../Arabidopsis_pg/Arabidopsis_pg.gfa -o -t 20`

But it is crashing and it doesn't produce any output (I installed vg tools using conda).
I would like to try gfa-wp, could you please give me more informations?

Thank you so much!

Lia

**Comment by ekg** [comment]
You give gfa-wp the minigraph cactus output and it should convert it into
GFAv1 format following PanSN naming and P-line for paths. This is
compatible with odgi and other tools that use path lines (it's still
compatible with VG as well).

Then you should be able to load it into odgi build. If the paths are in
W-lines they won't load, but the format conversion is trivial.

**Comment by AndreaGuarracino** [comment]
To be sure that is a system problem and not a graph problem, can you try with the graph available in `odgi` repository? This one https://raw.githubusercontent.com/pangenome/odgi/master/test/chr6.C4.gfa

`dgi sort -i chr6.C4.gfa -Y -o chr6.C4.sorted.og`

**Comment by LiaOb21** [comment]
It probably worked, I think:

```
odgi sort -i chr6.C4.gfa -Y -o chr6.C4.sorted.og -t 16 -P
[odgi::sort] warning: the given file "chr6.C4.gfa" is not in ODGI format. To save time in the future, please use odgi build -i=[FILE], --idx=[FILE] -o=[FILE], --out=[FILE] to generate a graph in ODGI format. Such a graph can be supplied to all ODGI subcommands. Building graph in ODGI format from given GFA.
[odgi::gfa_to_handle] building nodes:  -nan% @ 0.00e+00/s elapsed: 00:00:00:00 remain: -2147483648:-3:-14:-8
[odgi::gfa_to_handle] building edges:  -nan% @ 0.00e+00/s elapsed: 00:00:00:00 remain: -2147483648:-3:-14:-8
error [xp]: Graph to index is not optimized. Please run 'odgi sort' using -O, --optimize.


odgi sort -i chr6.C4.gfa -Y -o chr6.C4.sorted.og -t 16 -P -O
[odgi::sort] warning: the given file "chr6.C4.gfa" is not in ODGI format. To save time in the future, please use odgi build -i=[FILE], --idx=[FILE] -o=[FILE], --out=[FILE] to generate a graph in ODGI format. Such a graph can be supplied to all ODGI subcommands. Building graph in ODGI format from given GFA.
[odgi::gfa_to_handle] building nodes:  -nan% @ 0.00e+00/s elapsed: 00:00:00:00 remain: -2147483648:-3:-14:-8
[odgi::gfa_to_handle] building edges:  -nan% @ 0.00e+00/s elapsed: 00:00:00:00 remain: -2147483648:-3:-14:-8
path_sgd_zipf_space_max: 100
path_sgd_zipf_max_number_of_distributions: 101
[odgi::path_linear_sgd] 1D path-guided SGD:  -nan% @ 0.00e+00/s elapsed: 00:00:00:00 remain: -2147483648:-3:-14:-8


ls -lh
total 2.1M
   2.1M Jul 14 15:56 chr6.C4.gfa
   60 Jul 14 15:58 chr6.C4.sorted.og
```

**Comment by LiaOb21** [comment]
Thank you @AndreaGuarracino!

```
odgi version
v0.7.3 "Fissaggio"
```
It should be the latest one, right?

**Comment by subwaystation** [comment]
Yes, it is the latest release @LiaOb21.

I just tried your commands with the latest ODGI from todays master and the `v0.7.2 - Radler`. Both times it worked flawlessly.

```
odgi build -g Arabidopsis_pg.gfa -o Arabidopsis_pg.og -P -t 8
[odgi::gfa_to_handle] building nodes:  0.00% @ 3.60e+05/s elapsed: 00:00:00:00 
[odgi::gfa_to_handle] building nodes:  3.15% @ 1.50e+06/s elapsed: 00:00:00:00
...
[odgi::gfa_to_handle] building paths: 100.00% @ 1.46e+01/s elapsed: 00:00:00:02 remain: 00:00:00:00

odgi sort -i Arabidopsis_pg.og -Y -o Arabidopsis_pg.og.Y -P -t 15
path_sgd_zipf_space_max: 100
path_sgd_zipf_max_number_of_distributions: 101
[odgi::path_linear_sgd] calculating linear SGD schedule (4.10571e-13 1 100 0 0.01)
[odgi::path_linear_sgd] calculating zetas for 102 zipf distributions
[odgi::path_linear_sgd] 1D path-guided SGD:  0.00% @ 1.35e+04/s elapsed: 00:00:0
...
[odgi::path_linear_sgd] 1D path-guided SGD: 100.00% @ 1.31e+07/s elapsed: 00:00:01:33 remain: 00:00:00:00
```

Did you use a python 3.10 environment with conda? If so please switch to 3.9.
Since you can't use docker, can you at least use singularity?

**Comment by subwaystation** [comment]
![Arabidopsis_pg og Ys](https://user-images.githubusercontent.com/10184961/179077836-f75d4a2a-4ee0-4904-bc95-b16ef4f971cc.png)

```
odgi sort -i Arabidopsis_pg.og -p Ys -o Arabidopsis_pg.og.Ys -P -t 16
```

Including a buggy topological sort in the pipeline, it would look quite neat, however, the topological sort moves some nodes to the right (which it shouldn't!), so lot's of long range links are introduced.

**Comment by LiaOb21** [comment]
Hi @subwaystation,

Thank you so much! 
Here my python version, which should be ok:
```
python --version
Python 3.9.12
```
I can try to build from source if you think this could help to solve the problem. Using singularity it is not easy in our system apparently!

**Comment by LiaOb21** [comment]
I found that conda is not installing the right C++ version automatically. This is the version that I had:
```
gcc --version
gcc (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)

g++ --version
g++ (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)
```
So, I installed in the odgi conda environment a newer version of C++. 
```
conda install -c conda-forge gcc
conda install -c conda-forge gxx

gcc --version
gcc (conda-forge gcc 12.1.0-16) 12.1.0

g++ --version
g++ (conda-forge gcc 12.1.0-16) 12.1.0
```
Anyway, the problem is persisting. Is there any other dependency I should check before of trying to build the package from source?

**Comment by subwaystation** [comment]
Hi @LiaOb21,

the idea I had in mind was to build ODGI from scratch not using any conda dependencies. This will then tell us if the conda package is the problem or rather your setup.

Would that be somehow possible? Instructions are at https://odgi.readthedocs.io/en/latest/rst/installation.html#building-from-source.

Best,
Simon

**Comment by subwaystation** [comment]
Any updates @LiaOb21?

**Comment by LiaOb21** [comment]
Hi Simon,

Sorry for having been silent for so long.
I moved my work to another server, and I installed odgi using Docker there. However, when trying to sort the graph with -Y I had exactly the same error I had with odgi installed through conda. 
I will try now to install it from source in this new machine, hopefully here it will work. I'll keep you updated.

Cheers,

Lia

**Comment by LiaOb21** [comment]
Hi,

I think I was finally able to correctly install odgi via the guix-genomics git repository.
So far I tried just to sort the graph available in odgi repository, as suggested by @AndreaGuarracino.
Here the figures I obtained:

`odgi viz -i chr6.C4.og -o chr6.C4.png`

![chr6 C4](https://user-images.githubusercontent.com/96196229/192977024-013d1b42-d519-48fc-8ee3-72ea270c7d2a.png)

`odgi viz -i chr6.C4.sorted.og -o chr6.C4.sorted.png`

![chr6 C4 sorted](https://user-images.githubusercontent.com/96196229/192977196-b124b54f-0aa2-4702-bce8-7b3da6462f93.png)

I will then try with my pangenome. Can you confirm it is working properly now?
Thank you in advance.

Cheers,

Lia

**Comment by subwaystation** [comment]
Awesome! Thanks for your trials!

**Comment by shangshanzhizhe** [comment]
Hello all,

I encountered the identical problem -- sort didn't work with -Y option. Below is the details:

I was using Singularity package pulled from dockerhub, label 1688452591.

The commands were:

```singularity exec --cleanenv -H $PWD -e ~/scratch/apps/singularity_packages/odgi.simg odgi build -g 30044_12.scaffold_1.gfa -o 30044_12.scaffold_1.og -P```

which worked well.

Sort command was:
```singularity exec --cleanenv -H $PWD -e ~/scratch/apps/singularity_packages/odgi.simg odgi sort -i 30044_12.scaffold_1.og -o 30044_12.scaffold_1.sorted.og --threads 2 -P -Y```

Gave the error message:
```odgi: /odgi/build/sdsl-lite-prefix/src/sdsl-lite-build/include/sdsl/int_vector.hpp:1360: sdsl::int_vector<<anonymous> >::reference sdsl::int_vector<<anonymous> >::operator[](const size_type&)
 [with unsigned char t_width = 1; sdsl::int_vector<<anonymous> >::reference = sdsl::int_vector_reference<sdsl::int_vector<1> >; sdsl::int_vector<<anonymous> >::size_type = long unsigned int]:
 Assertion `idx < this->size()' failed.```

And It turned out that this only occurs when `-Y` is used. 

Would you be able to provide some suggestions?

Many thanks,
Shangzhe

**Comment by subwaystation** [comment]
Maybe you need to set the temporary directory with `-C` specifically? I also ran into some troubles running odgi on our cluster using Singularity. This was fixing my issues.
Were you able to try this out not using Singularity?

**Comment by shangshanzhizhe** [comment]
Thank you very much for the prompt reply!

Sadly the error message stills identical with `-C` added.  I tried both `sbatch` and `salloc` (to simulate a local machine) but both failed.

Any ideas?

Thanks,
Shangzhe

**Comment by shangshanzhizhe** [comment]
Thanks for the assistance!! 
Here is the link: [](https://drive.google.com/file/d/1jETaidm2FClsjfrGkIcEpApzF9leDw14/view?usp=sharing)
The original file I mentioned was a couple Gb so I shared a shorter scaffold here.

**Comment by subwaystation** [comment]
Hi @shangshanzhizhe,
your input graph contains `W` lines which are not supported by ODGI. We only support the GFA format where paths are encoded with `P` lines. 
With `vg convert` you can go from `W` to `P`, but wenever tried if ODGI can work with such a file. Feedback welcome!

**Comment by glennhickey** [comment]
Please also note that [minigraph-cactus can now produce ODGI output directly](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/pangenome.md#odgi) with `--chrom-og` for chromosome graphs and/or `--odgi` for the full genome graph.

**Comment by shangshanzhizhe** [comment]
Hello @subwaystation, 

You were correct. It turned out to be the problem of the GFA version. I haven't tried the `odgi sort` deeply but a basic test with `-Y` worked when GFA v1.0 was used. 
I
And also thank you @glennhickey for the suggestion. I'm using a older version of cactus-pangenome but I will explore it.

Many thanks,
Shangzhe

**Comment by subwaystation** [comment]
Happy to hear this is solved @shangshanzhizhe 

Cool feature @glennhickey !
