### ISSUE TITLE
W lines and P lines - visualizing output from cactus pangenome pipeline

### ISSUE THREAD

**Issue by agolicz** [pangenome/odgi#437]
Hi,
I've built a graph with cactus pangenome pipeline and wanted to visually compare with pggb using odgi viz. However, in the cactus pipeline, other than the reference contigs paths stored as P-lines all other paths are listed as haplotype threads (W-lines). But it looks like these are not visualized as paths by odg viz. Is there a quick way to convert W-lines to P-lines?
Thanks!
Agnieszka

Cactus pangenome pipeline output: https://get.massive.app/01G9F4NMSDQR3A0TCD1FZ4A1Q9?secret=hfGzIuSGFpDIOHnB

**Comment by agolicz** [comment]
Looks like I might have found me answer...
I'll try https://github.com/pangenome/gfa-wp

**Comment by agolicz** [comment]
Yep, works!

**Comment by AndreaGuarracino** [comment]
![image](https://user-images.githubusercontent.com/62253982/182368596-aa4e57ba-fbff-4e19-a8e9-2b9fd2ffccc1.png)

**Comment by agolicz** [comment]
Oh my childhood favorite :P. Thanks anyways, I'm sure I'll be back!
