### ISSUE TITLE
Compressed mode option for odgi viz not available

### ISSUE THREAD

**Issue by danielle-khost** [pangenome/odgi#441]
Hi there!
Quick question , I was looking to use odgi viz to get a compressed view of coverage using the -O flag, as my graph is fairly large (60+ haplotypes). However, neither the -O nor --compressed-mode flags are recognized, and in fact are not listed in the usage message. I checked the version and I believe I am on the latest release (v0.7.3 "Fissaggio"). I installed odgi using the bioconda recipe, for reference. Could there be an issue with my install?
Thank you!
-Danielle

**Comment by AndreaGuarracino** [comment]
Hi @danielle-khost, the `-O/--compressed-mode` flag is not available on bioconda yet, it will be there in the next release. In the meantime, you can use the compressed view by building `odgi` [from the source](https://github.com/pangenome/odgi#building-from-source) or using the last [Docker image](https://github.com/pangenome/odgi#docker).

**Comment by danielle-khost** [comment]
Awesome, thank you!
