### ISSUE TITLE
Node counts meaning

### ISSUE THREAD

**Issue by sivico26** [pangenome/odgi#444]
Hello there,

Thanks for developing `odgi`

I have been playing around with it a bit and developing some Python classes to work with the depth of the paths of one pangenome I produced using `pggb`. I generated the depth of each path on the nodes with the following `odgi` command:

```
odgi paths -i my_pengenome.og -H 
```

Which produces a supremely wide file of `PATHSxNODES` (as a suggestion, please consider to transpose this matrix to `NODESxPATHS` to be friendlier with Unix tools), On this file the first 3 columns are "path.name", "path.length", and "node.count". These columns should be sort of transparent, and at first, I thought their meaning was obvious. 

However, recently I got a surprise that led me to question the "node.count" column. I inferred that "node. count" meant the number of nodes that are being transversed by a given path in the pangenome. This would imply that in this `PATHSxNODES` binary matrix if I sum the values along the rows (the paths) I should get a `PATHSx1` array where the sum should be equal "node.count" column. This holds true for the `DRB1-3123` test data that is used in several of the `odgi` tutorials. 

The surprise came when I realized that the above assertion does not hold for my pangenome. I had coded my Python class to hold this assumption but it started to raise errors. When I checked, these are some of the values I got:

Node.counts: 15789405, 17355210, 17085290
Sum along the Path rows: 15642360, 17165197, 16906883

As you can see the sum is slightly lower than the Node counts, like "missing" presence on some nodes. So my questions are, did I infer the meaning of "node.count" correctly? If so, should it be possible to have instances where the above values do not match? If so, why would it be the case, or what does this say about my paths/graph?

There is also the possibility that this should not happen and that there is a mistake somewhere, but I wanted to consult with you first. My pangenome was normalized and sorted by `odgi` before using `odgi paths`.

I would really appreciate your thoughts on this matter.

Thanks for developing and maintaining `odgi`
Sivico

**Comment by sivico26** [comment]
The values I presented above are just 3 of the paths of my pangenome. In case it is useful here are the others:


Path |Hcom_1_chr1H|Hcom_1_chr2H|Hcom_1_chr3H|Hcom_1_chr4H|Hcom_1_chr5H|Hcom_1_chr6H|Hcom_1_chr7H|Hpat_1_chr1H|Hpat_1_chr2H|Hpat_1_chr3H|Hpat_1_chr4H|Hpat_1_chr5H|Hpat_1_chr6H|Hpat_1_chr7H|Hpub_1_chr1H|Hpub_1_chr2H|Hpub_1_chr3H|Hpub_1_chr4H|Hpub_1_chr5H|Hpub_1_chr6H|Hpub_1_chr7H
----------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------
Node.count|15789405|21514812|18909568|20895082|16797195|15969681|18822075|17355210|22773409|20502939|22547706|18137468|17562550|21016622|17085290|22673442|20395995|22699762|17929157|17509920|20619765
Sum along paths |15642360|21294465|18727692|20731212|16681970|15813911|18596713|17165197|22554631|20321919|22351382|17947452|17386983|20777006|16906883|22446247|20197717|22497175|17787999|17302692|20403280

To add some context, this pangenome has 3 species of the same genus, all of which have 7 chromosomes. There is a Path per combination of species and chromosome.

I hope it helps.
Sivico

**Comment by subwaystation** [comment]
Hi there @sivico26,

Taking a look at the code https://github.com/pangenome/odgi/blob/a2a595f24d7f16297b071312f666fa5a0f9909b4/src/subcommand/paths_main.cpp#L156-L177 `node.count` is the number of steps of each path. It is possible that a path can cross a node several times. On first glance, I can't identify any bug.

Could you please share your code? Thanks!

**Comment by sivico26** [comment]
Hi @subwaystation,

That clarifies things for me, as some nodes can appear more than once in a path, this will reflect in a lower "Sum along paths" in the binary matrix. 

Effectively, when I count from the paths, I get the "node.count" numbers.

Thanks for the clarification.

I guess the issue is resolved and my code is no longer necessary, but let me know if that is not the case.
Regards

**Comment by subwaystation** [comment]
Hi @sivico26 

Glad to hear that we solved this without further debugging ;)

I just pushed an update to master which changes `node.count` to `path.step.count` to make it more clear.

So I see this as solved.
