### ISSUE TITLE
hifiasm GFA to OG

### ISSUE THREAD

**Issue by jiadong324** [pangenome/odgi#504]
Dear Developer,

I want to convert GFA to OG with odgi. The GFA file was the output of hifiasm. The command line is ```odgi build -g hifiasm.p_ctg.gfa -o hifiasm.p_ctg.og```. 

The error message is listed below:
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stol
Aborted (core dumped)
```

Looking forward to your reply, thanks!

**Comment by AndreaGuarracino** [comment]
Hi @jiadong324, `odgi` supports a subset of the GFA format. It needs integers as segment (node) IDs. If you hack the GFA files by changing segment IDs, you should be able to get an `odgi` graphs.
