### ISSUE TITLE
odgi heaps for subsets of samples

### ISSUE THREAD

**Issue by mb47** [pangenome/odgi#505]
Hi,

I would like to run odgi heaps on various subsets of samples in my graph, as opposed to running it for the full set of samples -- is this possible without having to generate new graphs altogether?

thanks
Micha

**Comment by AndreaGuarracino** [comment]
Hi @mb47, this is possible with the following option:

```shell
 -b[FILE], --bed-targets=[FILE]    BED file over path space of the graph,
                                          describing a subset of the graph to
                                          consider.
```

You can use `odgi path -lL ...` to get an input BED file and `grep` only the paths that you want. Something like:

```shell
odgi heaps -i graph.og -b <(odgi paths -i graph.og -Ll | grep ... | awk -v OFS='\t' '{print($1,$2-1,$3)}')
```

**Comment by AndreaGuarracino** [comment]
That's a problem with `odgi heaps` interface. Try to group paths by sample (`-S`) or haplotype (`-H`) and you will get an output. However, I've just pushed a fix (https://github.com/pangenome/odgi/pull/509) to avoid empty output when no grouping is specified.

**Comment by mb47** [comment]
Great - works like a charm now! Many thanks.
