### ISSUE TITLE
odgi similarity segfault with multiple threads

### ISSUE THREAD

**Issue by ASLeonard** [pangenome/odgi#519]
Hi,

Running similarity with multiple threads segfaults, like
```
odgi similarity -t 2 -i graph.og
```

whereas this command runs as expected
```
odgi similarity -t 1 -i graph.og
```

I got lost diving into the handlegraph parts, but explicitly setting `omp_set_num_threads(1);` right before this line then allowed the program to finish as expected with correct output. I'm not sure why the critical section isn't keeping this safe with multiple threads, but even wrapping the entire section with `#pragma omp single` also did not fix the segfault, so maybe the handlegraph code isn't respecting the pragma correctly?

https://github.com/pangenome/odgi/blob/d339b531870f52103a0f86a4f82df8b30d79a784/src/subcommand/similarity_main.cpp#L202

This was done using the current head (`v0.8.3-32-gd339b531`).

Best,
Alex

**Comment by ASLeonard** [comment]
Changing the parallel parameter from `true` to `false` inside the `for_each_handle` call also removes the segfault, so definitely something happening inside that call.

**Comment by AndreaGuarracino** [comment]
It's strange. Do you get a segfault with any graph? The problem doesn't happen to me. Is something related to your system and/or GCC/cmake versions?

**Comment by ASLeonard** [comment]
It seemed to happen on quite a few different extracted graphs. I'll install `odgi` off conda and see if it happens on that version or on more stable graphs

**Comment by ASLeonard** [comment]
The conda version of odgi also caused a segfault.

I've hosted the `.og` and converted `.gfa.gz` [here](https://polybox.ethz.ch/index.php/s/NxqwXJKh4RXF5or), so if you are to run parallel similarity without a segfault, I can look more at the cmake build and see if something weird is happening with pthreads/omp/syscalls

**Comment by ekg** [comment]
This is some cruft due to our past attempts to make the graph fully dynamic
during editing.

It is strange though. We can test.

**Comment by AndreaGuarracino** [comment]
I can trigger the issue. I'll push a fix soon.

**Comment by AndreaGuarracino** [comment]
@ASLeonard [this fix](https://github.com/pangenome/odgi/pull/520/commits/4e77a5e503ddc09c2f41374a71c7bb13f022fbba) in #520 solved the segfault for me. Could you confirm that?

**Comment by ASLeonard** [comment]
Works like a charm on the `.og` and `.gfa` that were crashing earlier.

Thanks!

**Comment by subwaystation** [comment]
:hotsprings:
