### ISSUE TITLE
question on discrepancy between 1D and 2D visualization

### ISSUE THREAD

**Issue by jyj5558** [pangenome/odgi#524]
Hi, thanks for developing and maintaining such a helpful package.

I am now test-running Minigraph-Cactus pangenome workflow and odgi visualization for my learning purpose first,
and am confused about 1D and 2D plots I got from M-C workflow. Two plots for a chromosome are attached here.
The last row is the reference assembly (more contiguous) and the other rows above it are samples (more fragmented; these are contig-level assemblies as I don't have any more contiguous assemblies, yet).
![NW_026294758 1 full viz](https://github.com/pangenome/odgi/assets/91637442/63ca86fc-8a87-449b-973c-165a8c494d24)
![NW_026294758 1 full draw](https://github.com/pangenome/odgi/assets/91637442/407a9ac6-664a-4084-b752-a4a703f858a5)

In the 1D plot I see many links under the rows but I cannot see them in the 2D plot. 
From what I understood those links represent structural variants (right?), so I wonder if these links are just shown in this 1D plot to display what was found different across samples but the real structure of this chromosome region itself is shown as the 2D plot (except a small bubble).
As I will call and genotype structural variants in a later step after short-read mapping, I don't want the links in the 1D plot to be recognized as structural variants by themselves in, for example, a vcf file in this graph genome, while I just want the contigs aligned and anchored as nodes on the graph genome, more like what I see in the 2D plot. 
If the 1D plot is right, I think the graph genome has been suffered from the fragmented nature of samples and is presenting a wrong graph structure, or if the 2D plot is more right, I think I can consider the links in the 1D plot are presenting just apparent structural variation among samples and this chromosome is good to go to the read mapping step.
Could you guide me how to interpret this difference in the 1D and 2D plots? 

Thanks,

**Comment by AndreaGuarracino** [comment]
You can trust the 2D visualization and don't worry about variant calling. The 1D plot is showing those long links because of a bug in the sorting algorithm that is positioning several nodes in the wrong positions. I think other 1D visualizations, where you color paths differently, would further confirm that.

**Comment by jyj5558** [comment]
Your fast reply makes my life a lot relieved! Thanks so much and have great day.
