### ISSUE TITLE
order of species in odgi viz 

### ISSUE THREAD

**Issue by isabelladistefano** [pangenome/odgi#530]
Hi Andrea

I have my pangenome graph:

odgi viz -i allsixaccessions_chr8.fasta.gz.ceb3157.417fcdf.9fb5d42.smooth.final.og --colorbrewer-palette=[Set3:6] -o odgi_31_08_chr8_colortest30.png -x 2000

However I would like the order of the accessions to be changed. I am confused how to use -p, --paths-to-display option. This is also the same for the PAVs

Please advise me.

Best wishes,

Isabella

**Comment by subwaystation** [comment]
What is unclear about `-p, --paths-to-display`. Just write in each line of a file the path names in the order you desire.
