### ISSUE TITLE
Out of source build drops artifacts in source tree

### ISSUE THREAD

**Issue by adamnovak** [pangenome/odgi#54]
I checked out ODGI and did an out of source tree build, as is recommended for cmake projects:

```
mkdir build
cd build
cmake ..
make -j8
```

I ended up with the odgi binary in `bin` under the root of the project, not in `build/bin` where it should have ended up.

**Comment by ekg** [comment]
It's meant to end up in bin/. Is there a problem with this?

It's hopefully clear that I don't really know the right way to use cmake.

**Comment by adamnovak** [comment]
Yeah, I don't think putting it in the top-level bin all the time is right.

The point of building in a subdirectory is so that all the objects and
artifacts end up in that subdirectory. Then you can delete the
subdirectory to clean up the build, and you can keep different builds
around maybe with different configurations.

**Comment by subwaystation** [comment]
@ekg Do we want the Binary to live in the build directory, too?
Lot's of downstream code to correct, then.

**Comment by adamnovak** [comment]
I think my stance may have softened on this; for libbdsg we're also dropping the libs in the top level project lib directory, whether we do an out of source build or not.

**Comment by subwaystation** [comment]
Thanks for the feedback @adamnovak !
So we can close this one.
