### ISSUE TITLE
bed file 

### ISSUE THREAD

**Issue by ZiliaMR** [pangenome/odgi#561]
Hello, 

I am conducting an analysis with Helicobacter pylori genomes. Initially, I performed the analysis with a small dataset (n=21) and now have some queries regarding result visualization. I aim to zoom into a specific region containing genes of interest, but it seems I need to utilize either the BED or GFF file format for this purpose. My question is, are these files obtained from the annotation process? If so, which one from my dataset (n=21) should I utilize?

Thanks in advance

**Comment by ekg** [comment]
You can use annotations over any of the genomes you've put into the pangenome graph. These annotations would be derived by any method that could make them, either in silico or based on RNA analyses, or comparative genomics. In odgi, a BED file can be used to collect a subgraph of interest (odgi extract) or to guide different processes (like odgi depth), or to affect visualization (odgi draw). Let me know if this helps explain.

**Comment by subwaystation** [comment]
My first guess would be that you ran out of RAM. SEQWISH occupied over 125G when it crashed. Put something like `--transclose-batch 10000  --resume`  and you should find out quickly if this was the limiting factor.
