### ISSUE TITLE
odgi heaps

### ISSUE THREAD

**Issue by jwli-code** [pangenome/odgi#579]
Hi, “Summing up, we called odgi heaps -i <graph.gfa> -S -n200 to generate pangenome saturation curves for 200 permutations. ” From the article “A draft human pangenome reference”。
But when I try to run with my data, the result is empty, what is going on.
`odgi heaps -i XXX.og -S -n200 -t 40 -P`

**Comment by subwaystation** [comment]
Without having access to your data it's hard to tell. I would recommend https://github.com/marschall-lab/panacus instead. It will give you the exact result (no permutations required!) much faster.
