### ISSUE TITLE
Issue with ODGI sort and viz

### ISSUE THREAD

**Issue by MatteoSebastianelli** [pangenome/odgi#588]
Hello!

I am trying to visualize a pangenome graph I generated using the HPRC pipeline. In the last step of the pipeline (cactus-minigraph-join) I included the --viz flag to output pangenome plots for each chromosome. Here I paste an example:
![1 full viz](https://github.com/user-attachments/assets/5c603455-be57-469d-a846-3453300d0692)

However, from what I understand this pangenome is not sorted. So, I ran odgi sort with the -P and -Y options to simplify the graph on the --chrom-og output, but the result its weird, and shows each individual path for each individual sample in a separate row.
![1A full sorted](https://github.com/user-attachments/assets/5d97bc77-e574-4ed8-83fb-48bf4cb07c9c)

How can I compact all the paths in order to obtain a figure similar to the first (but sorted)?

Here are the commands used to generate the last plot:

odgi sort -i $PACBIO/pangenome/finch_pg_final/finch_pangenome.chroms/1A.full.og --threads 2 -P -Y -o $PACBIO/pangenome/finch_pg_final/finch_pangenome.chroms/1A.full.sorted.og

odgi viz -i $PACBIO/pangenome/finch_pg_final/finch_pangenome.chroms/1A.full.sorted.og -o $PACBIO/pangenome/finch_pg_final/finch_pangenome.chroms/1A.full.sorted.png -x 500 -d -u

Thanks in advance!
Matteo

**Comment by AndreaGuarracino** [comment]
The 1st one is a compressed representation. To generate the same, you need to prepare a file with all prefixes

```shell
odgi paths -i $PACBIO/pangenome/finch_pg_final/finch_pangenome.chroms/1A.full.sorted.og -L | cut -f 1,2 -d '#' | sort | uniq > prefixes.txt
```

and use them to merge contigs by sample and haplotype:

```shell
odgi viz -i $PACBIO/pangenome/finch_pg_final/finch_pangenome.chroms/1A.full.sorted.og -o $PACBIO/pangenome/finch_pg_final/finch_pangenome.chroms/1A.full.sorted.merged.png -x 500 -d -u -M prefixes.txt
```

**Comment by MatteoSebastianelli** [comment]
Thanks Andrea, it worked!

Best,
Matteo
