### ISSUE TITLE
dynamic path positions

### ISSUE THREAD

**Issue by ekg** [pangenome/odgi#59]
I want to make odgi into MutablePathPositionHandleGraph. This will help with a ton of things, including graph sorting.

It should be possible to maintain path positions through editing operations. But it will be tricky and will require tests.

**Comment by jeizenga** [comment]
I've been thinking about doing this on PackedGraph for a while too. I can't think of any way to do it without logarithmic edits to the paths though, which is maybe not so terrible.

**Comment by ekg** [comment]
I thought to do this by editing path positions that are cached per node.
Wouldn't this be ~O(1)?

**Comment by ekg** [comment]
I mean that this would be so in odgi

**Comment by jeizenga** [comment]
I think the real kicker is the "edit in the middle" operations on the paths. If you stick to editing the paths on the two ends then caching positions is probably sufficient. You still need a lookup by position though, which I think would be tough without a logarithmic algorithm. On XG we use a compressed rank/select bit vector for this, which I think is pretty clever. Not very dynamic though. Maybe DYNAMIC has a solution?

**Comment by ekg** [comment]
Of course, I was only thinking about half of the problem. Sorry for being
dense.

In DYNAMIC you'd just set or unset bits in a bitvector. But you're correct:
this is probably going to have a logarithmic component, in the sense that
you have to look up the location and modify the supporting partial sums
running down the tree.

**Comment by jeizenga** [comment]
Sounds pretty much like the rope data structure

**Comment by subwaystation** [comment]
I don't think we need to have this in `odgi` at the moment. Closing. We can re-open later if needed.
