### ISSUE TITLE
Extracting node coordinates on paths

### ISSUE THREAD

**Issue by bslbgg** [pangenome/odgi#592]
Hi all, I probably miss something very fundamental, but I can't figure out how to extract the mappings of individual nodes on the path sequences using odgi. 

Starting point is a given og file which was created from a set of contigs derived from various individuals of a clade using pggb. Is there a simple procedure to get information (start/stop/strand) on the exact location of the nodes on the individual contigs?

Any help would be greatly appreciated, thanks!

**Comment by AndreaGuarracino** [comment]
Here you are! https://odgi.readthedocs.io/en/latest/rst/tutorials/navigating_and_annotating_graphs.html#graph-to-path-position-mapping
