### ISSUE TITLE
Adding annotations via gff

### ISSUE THREAD

**Issue by buchanri** [pangenome/odgi#597]
Hello, I'm interested in adding annotations to my gfa graph via csv using `odgi position`. I have 4 bacteria genomes and my question is since ` odgi position -E` only allows for one gff, should I only add one of the genomes gff or somehow combine all 4 gff's of the genomes to make the csv?

Thank you for any feedback.

**Comment by subwaystation** [comment]
I would add all 4 annotations into 1 GFF. This should output a CSV where the annotation column is unique across your 4 bacteries. If you run `odgi position` 4 times, you might see an overlap which might be tricky for BandageNG.
