### ISSUE TITLE
odgi-layout: running with GPU acceleration shows no output

### ISSUE THREAD

**Issue by Shihab-Shahriar** [pangenome/odgi#598]
Hi,

I have been trying to use gpu-accelerated odgi-layout command, but running the command as outlined in README leaves me hanging with no output, even with a -P flag. After several minutes, I see no GPU activity on `nvidia-smi`, or any CPU activity on `htop`- a single thread seems to be running when 16 threads were specified using `--threads`.

I have no prior experience using odgi, but I have gone through the quick start guide and tutorials. i would love to reproduce the results from the [paper](https://arxiv.org/pdf/2409.00876), any help would be highly appreciated.

`./odgi layout -i chr8.pan.og -o out.lay --threads 8 --gpu -P`

Ubuntu 22.04, CUDA 12.4, V100 GPU.

(Note that compiling without GPU support also has similar outcome- but that's somewhat understandable given that the CPU version for this human chr.8 graph takes more than an hour to complete, while GPU version should take less than 2 mins  (Table 7 from the paper)

**Comment by Shihab-Shahriar** [comment]
@tonyjie @nsmlzl @AndreaGuarracino

**Comment by Shihab-Shahriar** [comment]
@subwaystation , thanks for your reply. I'll retry.

I want to note that at one instance I gave up after 24 minutes. Do you have any estimate how long this initial index-building might take?

**Comment by subwaystation** [comment]
I don't know your hardware, so hard to estimate!
But hard disk speed is critical. The index is built using memory mapped data structures like https://github.com/ekg/mmmulti. 
Give it some hours, just to try.
You can also start with the chr20 graph. You might see something quicker,.

**Comment by tonyjie** [comment]
Hi @Shihab-Shahriar , 

Yes, the reason is most likely because it's building the path index of the pangenome graph during that time. For a large graph like chr8, it would take several minutes (~10 minutes in my memory) using 32-threads CPU. This is regarded as the data-preprocessing step, because when you have a graph `chr8.og`, you can directly build its path index as long as you have the `.og` graph by `odgi pathindex` (https://odgi.readthedocs.io/en/latest/rst/commands/odgi_pathindex.html)
```
odgi pathindex -i ${OG_FILE} -o ${PATH_FILE} -t ${NUM_THREAD}
```
Then when you run `odgi layout`, you can give the pre-built pathindex in `-X ${PATH_FILE}`, and it will skip the building path step. Then you should be able to generate the layout in minutes using GPUs. (Also you want to have `NUM_THREAD` to be larger, since there are also some CPU processing time that we use CPU multi-threading to accelerate). 
```
odgi layout -i ${OG_FILE} -o ${LAY_FILE} -X ${PATH_FILE} --threads ${NUM_THREAD} --gpu
```

**Comment by tonyjie** [comment]
In our artifact setting, the entire preprocessing time (including building pathindex) of the entire 24 human chromosome pangenomes takes 1-2 hours, mentioned [here](https://github.com/tonyjie/gpu_pangenome_layout_artifact/tree/main?tab=readme-ov-file#download-and-preprocess-the-dataset-need-250gb-disk-space-1-2-hours)
 
> This will download the raw data (.gfa file), and generate the required dataset (.og file and **.xp path index file**) using the other commands of ODGI. They will be saved into chroms/ and **path_index/ directories** mentioned above.
The expected reproduction time for downloading and generating all the dataset is 1-2 hours.

**Comment by Shihab-Shahriar** [comment]
@tonyjie , I had tried the pathindex command, on the smaller chr20 graph, but it didn't complete in 1hr 40m with 30 threads. 

I am now using the "dataset_preprocess.sh" script in [gpu_pangenome_layout_artifact](https://github.com/tonyjie/gpu_pangenome_layout_artifact) repo, only for chr20, but again, I get stuck. 

I had no error while compiling odgi, i guess I will look into the warnings for now.

**Comment by tonyjie** [comment]
This looks weird. Can you start with the smallest chromosome: ChrY?

**Comment by tonyjie** [comment]
As @subwaystation said, it's an IO-bound process, so if your disk is slow, it might be the case. But 2-hour pathindex generating looks too long for me. Is your CPU multi-threading working as expected?

**Comment by Shihab-Shahriar** [comment]
ChrY worked, but rest didn't.

I think I have a clue: if you sprinkle lots of prints at xp.cpp file, at [this line](https://github.com/pangenome/odgi/blob/f4c1671c203f5562cf56c9e2c0ee1617a9772284/src/algorithms/xp.cpp#L119), the program seems to get stuck. 

` node_path_ms.index(nthreads, graph.get_node_count() + 1);`

The `top` command suggests the process is spending most of it's time in Uninterruptible Sleep (D) State. 

here is a screenshot of the `top` output in case it provides any further clue:
![image](https://github.com/user-attachments/assets/9378d725-fdc0-4b55-a7aa-c1a6fef8123f)

**Comment by tonyjie** [comment]
I haven't encountered this issue before. @subwaystation do you know more about this part of `odgi pathindex`?

**Comment by subwaystation** [comment]
I also never saw this. A wild guess would be that the university cluster is somehow unhappy.
Else maybe @ekg has an idea? He wrote mmmulti.

**Comment by subwaystation** [comment]
How long did chrY take you @Shihab-Shahriar?

**Comment by Shihab-Shahriar** [comment]
That one takes about 3 seconds.

**Comment by Shihab-Shahriar** [comment]
@tonyjie do you have any index file that you can please share for a reasonably large graph? I would love to sidestep this whole issue if I can.

**Comment by tonyjie** [comment]
@Shihab-Shahriar I can try to share with you tonight.

**Comment by tonyjie** [comment]
@Shihab-Shahriar This is a compressed file for the path index of chr20: https://drive.google.com/file/d/1LwtALSyH76TEyOPfVh6jkwsWzxnBEaPn/view?usp=sharing
