### ISSUE TITLE
Playing around with 12 Arabidopsis thaliana genomes.

### ISSUE THREAD

**Issue by subwaystation** [pangenome/odgi#84]
These are the 12 _Arabidopsis thaliana_ genomes from @chrikub I run through `odgi sort` with options `bnSn`, `no_K` and `R` in `odgi viz`.

The data can be found on pg2: `/home/ubuntu/sh/ath_christian_kubica/chrk_12samples_odgi_1D_sort_bnSn_no_K_R`. @tpook92

![chrk_ath_12samples sorted og R no_K bnSn](https://user-images.githubusercontent.com/10184961/75662486-7870b900-5c6f-11ea-8017-0a37423bcdeb.png)
 
What I am confused about is that one can get the impression, that there is no real distinction between the sequences of the 5 chromosomes.... All chromosomes' sequences are below each other. I would have expected that they would consecutively build up to the right as in https://github.com/vgteam/odgi/issues/71#issuecomment-586171429. 

@ekg @chrikub @josiahseaman @6br

**Comment by subwaystation** [comment]
Now with `S`.
![chrk_ath_12samples sorted og R no_K S](https://user-images.githubusercontent.com/10184961/75681616-39089380-5c94-11ea-875b-86c350649863.png)

**Comment by subwaystation** [comment]
Now with "s".
![chrk_ath_12samples sorted og R no_K s](https://user-images.githubusercontent.com/10184961/75696054-3cf3e000-5cab-11ea-972c-91b40f1b334a.png)

**Comment by subwaystation** [comment]
A new round of sorting with new data from @chrikub: Filtered by 10kb. @tpook92 @josiahseaman @ekg 

`bnSn`
![chrk_ath_12samples sorted_10kb og R no_K bnSn](https://user-images.githubusercontent.com/10184961/76230124-88fed180-6223-11ea-93a4-6c2aa2b94503.png)
`S`
![chrk_ath_12samples_10kb sorted og R no_K S](https://user-images.githubusercontent.com/10184961/76230168-9916b100-6223-11ea-9bc3-5bc83c626e54.png)

`s`
![chrk_ath_12samples_10kb sorted og R no_K s](https://user-images.githubusercontent.com/10184961/76230077-797f8880-6223-11ea-8134-76646413cb82.png)

**Comment by AndreaGuarracino** [comment]
That's strange, why different chromosomes are so overlappings?

```
time odgi sort -i chrk_ath_12samples.og -o chrk_ath_12samples.Y.G10.og -Y -t 16 -P -G 10
[odgi::path_linear_sgd] calculating linear SGD schedule (2.82215e-13 1 30 0 0.01)
[odgi::path_linear_sgd] calculating zetas for 1091 zipf distributions
[odgi::path_linear_sgd] 1D path-guided SGD: 100.00% @ 1.66e+07/s elapsed: 00:00:26:45 remain: 00:00:00:00

real  28m37,085s
user  422m42,148s
sys  0m30,611s
```
![chrk_ath_12samples Y G10 sub](https://user-images.githubusercontent.com/62253982/97085986-12330f00-1621-11eb-8a79-6e5029911bda.png)


```
time odgi sort -i chrk_ath_12samples_10kb.og -o chrk_ath_12samples_10kb.Y.G20.og -Y -t 16 -P -G 20
[odgi::path_linear_sgd] calculating linear SGD schedule (7.8928e-13 1 30 0 0.01)
[odgi::path_linear_sgd] calculating zetas for 1091 zipf distributions
[odgi::path_linear_sgd] 1D path-guided SGD: 100.00% @ 1.36e+07/s elapsed: 00:00:39:33 remain: 00:00:00:00

real  40m46,451s
user  624m56,586s
sys  0m43,097s
```

![chrk_ath_12samples_10kb Y G20 sub](https://user-images.githubusercontent.com/62253982/97085907-b36d9580-1620-11eb-8bb7-a48fe5c95f78.png)

**Comment by ekg** [comment]
The alignment method allows too much sporadic collapse.

This is dealt with by setting a high segment parameter in edyeet, for
instance. It seems difficult to arrange in minimap2 alignments.

**Comment by subwaystation** [comment]
We are much farther now. The PG-SGD is successfully applied in https://github.com/pangenome/pggb.
